version: "3"
services:
  mudict:
    ports:
      - "127.0.0.1:5222:3000"
    build:
      context: .
      dockerfile: server.Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  mudict-client:
    ports:
      - "127.0.0.1:2462:3000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: client.Dockerfile
    restart: always

  db:
    image: postgres
    ports:
      - "2300:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=paring
      - POSTGRES_DB=mudict

  meilisearch:
    image: getmeili/meilisearch:v1.1.1
    restart: always
    volumes:
      - meili_data:/meili_data
    ports:
      - "7700"

volumes:
  pg-data:
  meili_data: