version: '3'
services:
  mdict:
    build:
      context: ..
#    deploy:
#      replicas: $TOTAL_REPLICAS
    depends_on:
      - db
#      - redis
#      - bridge
#      - proxy
#    volumes:
#      - /run/docker.sock:/run/docker.sock:ro
#      - ../config.deploy.json:/app/config.json:ro
#      - ./logs:/app/logs:rw
    restart: unless-stopped
    command: yarn prod

  db:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017"
    restart: unless-stopped

volumes:
  mongo:
