version: "3"
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=paring
      - POSTGRES_DB=mudict
    command: ['postgres', '-c', 'wal_level=logical']

  meilisearch:
    image: getmeili/meilisearch:v1.1.1
    restart: always
    volumes:
      - ./meili_data:/meili_data
    ports:
      - "7700:7700"

  meilisync:
    image: long2ice/meilisync
    volumes:
      - ./config.yml:/meilisync/config.yml
    restart: always

volumes:
  pg-data: